/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daftar user baru */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login, kembalikan token */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ambil profil user yang sedang login */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ubah profil user (parsial); mengembalikan token baru (ADR-022) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api/v1/me/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total poin, XP, dan level user */
        get: operations["getMyScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Streak berjalan & terpanjang */
        get: operations["getMyStreak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List quest milik user */
        get: operations["listQuests"];
        put?: never;
        /** Buat quest baru */
        post: operations["createQuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quests/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quest hari ini beserta status selesai/belum (hormati timezone user) */
        get: operations["getTodayQuests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quests/{questId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hapus / arsipkan quest */
        delete: operations["deleteQuest"];
        options?: never;
        head?: never;
        /** Ubah quest (parsial) */
        patch: operations["updateQuest"];
        trace?: never;
    };
    "/api/v1/quests/{questId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tandai quest selesai untuk hari ini (memicu penambahan poin) */
        post: operations["completeQuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quests/{questId}/uncomplete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batalkan penyelesaian hari ini (rollback poin) */
        post: operations["uncompleteQuest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Peringkat berdasarkan poin */
        get: operations["getLeaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            /** @description IANA timezone (mis. "Asia/Jakarta"). Opsional; server memakai "Asia/Jakarta" sebagai default bila tidak diisi. */
            timezone?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["UserResponse"];
        };
        /** @description Profil publik user. Tidak pernah menyertakan password_hash. */
        UserResponse: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            timezone: string;
        };
        /** @description Update parsial profil. Email tidak dapat diubah. */
        UpdateProfileRequest: {
            display_name?: string;
            /** @description IANA timezone (mis. "Asia/Jakarta"). */
            timezone?: string;
        };
        CreateQuestRequest: {
            title: string;
            note?: string;
            category: string;
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
        };
        /** @description Update parsial quest. */
        UpdateQuestRequest: {
            title?: string;
            note?: string;
            category?: string;
            /** @enum {string} */
            difficulty?: "easy" | "medium" | "hard";
            active?: boolean;
        };
        QuestResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            user_id: string;
            title: string;
            note?: string;
            category: string;
            /** @enum {string} */
            difficulty: "easy" | "medium" | "hard";
            recurrence: string;
            active: boolean;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Body kosong untuk MVP. */
        CompleteQuestRequest: Record<string, never>;
        QuestLogResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            quest_id: string;
            /** Format: uuid */
            user_id: string;
            /**
             * Format: date
             * @description Tanggal lokal user, mis. "2026-08-31".
             */
            date: string;
            status: string;
            points_awarded: number;
            /** Format: date-time */
            completed_at: string;
        };
        TodayQuestsResponse: {
            /**
             * Format: date
             * @description Tanggal lokal user, mis. "2026-08-31".
             */
            date: string;
            items: {
                quest: components["schemas"]["QuestResponse"];
                completed: boolean;
            }[];
        };
        ScoreResponse: {
            total_points: number;
            xp: number;
            level: number;
            points_to_next_level: number;
        };
        StreakResponse: {
            current: number;
            longest: number;
            /**
             * Format: date
             * @description Tanggal aktivitas terakhir (lokal user), atau null.
             */
            last_active?: string | null;
        };
        LeaderboardEntry: {
            rank: number;
            /** Format: uuid */
            user_id: string;
            display_name: string;
            points: number;
        };
        /** @description Amplop error konsisten dengan platform/httpx. Serialisasi: {"error":{"code":"...","message":"..."}}. Nilai `error.code` yang dipakai: email_taken, invalid_credential, user_not_found, quest_not_found, already_completed, not_completed, validation_failed, internal_error. */
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        HealthResponse: {
            status: string;
        };
    };
    responses: {
        /** @description Permintaan tidak valid (mis. validation_failed). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token tidak ada / tidak valid, atau kredensial salah. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource tidak ditemukan. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Konflik state (mis. already_completed / not_completed / email_taken). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Kesalahan internal server. */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description ID quest (UUID). */
        QuestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description User dibuat, token dikembalikan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Kredensial valid, token dikembalikan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profil user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Profil diperbarui, token baru dikembalikan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getMyScore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ringkasan skor user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getMyStreak: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Data streak user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    listQuests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar quest milik user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestResponse"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    createQuest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateQuestRequest"];
            };
        };
        responses: {
            /** @description Quest dibuat. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getTodayQuests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quest untuk tanggal lokal user beserta status penyelesaian. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayQuestsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    deleteQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quest dihapus / diarsipkan. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    updateQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestRequest"];
            };
        };
        responses: {
            /** @description Quest diperbarui. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    completeQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteQuestRequest"];
            };
        };
        responses: {
            /** @description Quest ditandai selesai, log dikembalikan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestLogResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
        };
    };
    uncompleteQuest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID quest (UUID). */
                questId: components["parameters"]["QuestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Penyelesaian hari ini dibatalkan. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            500: components["responses"]["Internal"];
        };
    };
    getLeaderboard: {
        parameters: {
            query?: {
                /** @description Jumlah maksimum entri yang dikembalikan. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daftar peringkat. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardEntry"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["Internal"];
        };
    };
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service hidup. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Internal"];
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service siap menerima traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Internal"];
        };
    };
}
